name = "Simply Modded"
author = "tjamesw123"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "014445da8dd3083fc73e0f3585d29e637c9e9c441a572bf7a48962ebea3e468c"

[versions]
fabric = "0.15.11"
minecraft = "1.19.2"
